import { ArrowRight } from "lucide-react";
import Button from "../components/Ui/Button";
import Card from "../components/Ui/Card";

const linkedInUrl =
  "https://www.linkedin.com/pulse/social-technology-take-cathrine-otieno-oeyve";

export default function WritingPage() {
  return (
    <div className="min-h-screen bg-white py-20 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-16">
          <h1 className="text-4xl md:text-6xl text-slate-900 mb-4 font-bold">
            Writing
          </h1>
          <p className="text-lg text-slate-600 max-w-2xl">
            Essays at the intersection of technology, ethics, and human
            connection. More essays are coming soon — for now, enjoy this
            featured piece.
          </p>
        </div>

        {/* Featured Essay Card */}
        <Card className="p-8 border-2 border-slate-200 hover:border-blue-200 transition-all rounded-xl mb-16">
          <div className="mb-4">
            <span className="text-sm text-slate-500">
              Dec 2025 · Tech Ethics · Digital Culture
            </span>
          </div>
          <h2 className="text-3xl md:text-4xl text-slate-900 mb-4 font-semibold">
            Social Technology and Social Take:  
            <span className="block">
              From Human Connection to Human Commodity — and the Possibility of
              Reclamation
            </span>
          </h2>

          {/* Excerpt */}
          <p className="text-slate-700 mb-6 italic">
            Social technologies began as bridges — tools meant to shrink
            distance and digitize human connection. Over time, the bridge became
            a marketplace, and users became commodities. This essay traces that
            evolution and explores what it means to reclaim agency in the
            digital future.
          </p>

          {/* FULL ESSAY CONTENT */}
          <div className="prose prose-lg max-w-none text-slate-800">
            <h3>1. Introduction: Technology as Bridge and Trap</h3>
            <p>
              Social technologies were not born as the villains of modern life.
              They began as bridges—simple tools meant to shrink distance, make
              connection easier, and digitize the social fabric we already
              carried within us. Over time, however, the bridge expanded into an
              empire, and the empire developed appetites. What started as a
              human project slowly became a commercial machine.
            </p>
            <p>
              Yet the story is not entirely tragic. Within the same systems that
              distort human connection, there are also opportunities to
              reimagine and reclaim it. This essay explores that evolution—how
              social technologies shifted from connection to commodification,
              and how emerging models offer alternative futures centered on user
              agency and conscious design.
            </p>

            <h3>2. Early Intentions: Connection as the Core Function</h3>
            <p>
              Early platforms—Facebook, WhatsApp, Snapchat, YouTube—were built
              with intentions that, while imperfect, were fundamentally
              relational. They did not create connection; they digitized it.
              They made expression accessible, communication immediate, and
              global interaction almost mundane.
            </p>

            <h3>3. The Shift: When Platforms Became Markets</h3>
            <p>
              The transformation began when connection proved profitable. The
              attention generated by billions of users became a commodity, and
              platforms reorganized themselves around extracting it. Algorithms
              evolved to maximize engagement, not well-being. Interfaces became
              optimized for stickiness, not clarity.
            </p>

            <h3>4. Data Monopolies and Asymmetric Power</h3>
            <p>
              Large platforms do not simply collect user data; they acquire it
              strategically. Facebook’s purchase of Instagram and WhatsApp was
              not aesthetic — it was political. These moves consolidated social
              graphs, behavioral patterns, and communication ecosystems under one
              corporate domain, creating a structure of asymmetric consent.
            </p>

            <h3>5. Analytical Blind Spots: Research That Misses the Root</h3>
            <p>
              Much public discourse looks at surface symptoms — misinformation,
              privacy scandals, screen time — without addressing the deeper
              incentive systems that generate them. True critique requires
              interrogating the architectures of closed ecosystems and
              profit-driven algorithmic design.
            </p>

            <h3>6. Proposed Solutions: Interoperability and Decomposition</h3>
            <p>
              Scholars propose decomposing large platforms by making data,
              social graphs, and messaging interoperable. This allows users to
              leave a platform without abandoning their entire social world —
              reclaiming digital autonomy.
            </p>

            <h3>7. Web3 and Tokenized Attention: A New Direction</h3>
            <p>
              Emerging Web3 models attempt to decentralize value. Instead of
              corporations owning attention, users tokenize and control it.
              While experimental, these models challenge centralized exploitation
              and put agency back into users’ hands.
            </p>

            <h3>8. Reclaiming the Digital Future</h3>
            <p>
              The crisis of social technology is not technological but ethical.
              With conscious design and conscious use, we can create systems
              that prioritize autonomy, dignity, and genuine connection.
            </p>

            <h3>9. Conclusion: Returning the Bridge to the People</h3>
            <p>
              We surrendered agency too quickly. But with interoperability,
              decentralized systems, and new attention models, we have the
              chance to redesign the digital future on our own terms. The point
              was never the platforms — it has always been the people who use
              them.
            </p>
          </div>

          {/* READ ON LINKEDIN BUTTON */}
          <Button
            onClick={() =>
              window.open(linkedInUrl, "_blank", "noopener,noreferrer")
            }
            className="bg-blue-600 hover:bg-blue-700 text-white mt-8 flex items-center"
          >
            Read on LinkedIn
            <ArrowRight className="ml-2 w-4 h-4" />
          </Button>
        </Card>

        {/* Coming Soon */}
        <div className="mt-16 p-8 bg-slate-50 border border-slate-200 rounded-xl">
          <h3 className="text-xl text-slate-900 mb-3 font-semibold">
            More essays coming soon
          </h3>
          <p className="text-slate-600">
            I’m building a small intimate blog experience. In the meantime, you
            can find more of my reflections and writing on my social platforms.
          </p>
        </div>
      </div>
    </div>
  );
}
